### ISSUE TITLE
Players without permission may ban any player

### ISSUE THREAD

**Issue by Grib4ik** [RezzedUp/OpGuard#1]
If you type /op <player> plugin will see it and will ban the player <player>.
Even without access to /op

**Comment by RezzedUp** [comment]
Disable punish.player-attempt in the config.

``` yml
punish:
  player-attempt: false
```

https://github.com/RezzedUp/OpGuard/wiki/Configuration-Guide#punish-section

---

Side note: it is **not** recommended to enable player-attempt punishments! _"Enabling this option is not recommended: innocent players are likely to be punished."_

**Comment by Grib4ik** [comment]
I need this feature :(
