### ISSUE TITLE
OPGuard generating conflicts with one of my plugins.

### ISSUE THREAD

**Issue by alexsatellite** [RezzedUp/OpGuard#10]
I got a report of a customer that one of my plugins is not working with yours. I checked and he's right.
I debugged it to find where the plugin breaks, and it breaks in a pathetic if - else statement inside of a command method.

https://hastebin.com/cicetiliva.java

It breaks in  `if (user.isInventoryPreLoaded()){`. it always returns false
this does not generate errors, etc but breaks some things of my plugin and clearly is not my fault. I recommend you to fix your plugin because it's checking for something that should not check.

debugged messages while executing the command twice:
This is my picture of how the plugin works without yours:
http://prnt.sc/dtj8ky
And this one is with your plugin:
http://prnt.sc/dtj8gt

**Comment by alexsatellite** [comment]
Well this can be fixed with  exempt-commands:
but should check anyway what you check in your plugin.

**Comment by RezzedUp** [comment]
Just to clarify, does `Main.getInstance().getUser(p);` retrieve User objects from a HashMap where player objects are keys? (`HashMap<Player, User>`)

**Comment by alexsatellite** [comment]
Yes
