### ISSUE TITLE
Update for 1.13

### ISSUE THREAD

**Issue by Guest1131** [RezzedUp/OpGuard#14]
Can you do an update of OPGuard for spigot 1.13 please?

**Comment by MattAnderson97** [comment]
it should already work for 1.13

edit:
just tested on latest version of spigot 1.13.2, no errors on server start

edit 2:
no immediate errors when using commands, should work fine for you

**Comment by Guest1131** [comment]
If it's not a mistake, in my opinion, it doesn't mean it's compatible..

**Comment by RezzedUp** [comment]
As far as I can tell, OpGuard is completely compatible with 1.13. If you have any errors, please post them.
