### ISSUE TITLE
OP list

### ISSUE THREAD

**Issue by WarnDa** [RezzedUp/OpGuard#18]
Hello,

I use this plugin as security on my server, and as minecraft account are often "hacked" I added a security on my server where I am deoped everytime I disconnect, and I need to reop myself using console everytime I connect.
But I wanted a feature "list of authorised players" where only the players from this list could be OPPED.

So it would avoid any problem with 'hacker' trying to op themselves.

**Comment by RezzedUp** [comment]
That's sorta what OpGuard already does: only verified operators (those who have received `op` from OpGuard directly) are allowed to *be* operators. As long as you keep the password private, no one else should be able to get `op`.
